#!/usr/bin/env bash
#
# gen-lab-topology.sh
#
# Collects live lab topology state from the Proxmox host and emits markdown
# to stdout. Intended to be run ON the Proxmox host (192.168.1.250).
#
# READ-ONLY. This script only reads state. It does not modify firewall rules,
# VM configuration, network settings, or anything else.
#
# Usage, on the pve host:
#     ./gen-lab-topology.sh > LAB-TOPOLOGY.md
#
# Usage, remotely without copying the file to the host:
#     ssh pve "bash -s" < tools/gen-lab-topology.sh > docs/project-knowledge/LAB-TOPOLOGY.md
#
# Commands whose output is unavailable (missing binary, permissions) are
# reported inline as UNVERIFIED rather than omitted or substituted.

set -uo pipefail

# Emit a section header followed by a fenced block containing command output.
# If the command fails or produces nothing, say so explicitly.
emit() {
    local title="$1"; shift
    echo "### ${title}"
    echo
    echo '```'
    if ! "$@" 2>&1; then
        echo "UNVERIFIED — command failed or is unavailable on this host: $*"
    fi
    echo '```'
    echo
}

# Lab bridges only. vmbr0 is the management/uplink bridge and its neighbour
# table contains the operator's own home/office LAN devices (workstations,
# router, phones) which are NOT part of the lab and must never be published.
# Never add vmbr0 to this list.
LAB_BRIDGES="vmbr10 vmbr20 vmbr30 vmbr40"

# Neighbour entries for lab bridges only.
# `ip neigh show dev X` omits the "dev X" field from its output, so it is
# reconstructed here to keep the familiar `IP dev BRIDGE lladdr MAC STATE`
# column order.
lab_neigh() {
    local b
    for b in ${LAB_BRIDGES}; do
        ip -4 neigh show dev "${b}" 2>/dev/null \
            | awk -v br="${b}" 'NF { ipaddr=$1; $1=""; sub(/^ +/,""); print ipaddr, "dev", br, $0 }'
    done
}

# `ip -br addr` with vmbr0's IPv6 link-local address redacted.
#
# A link-local address is derived from its interface's MAC via EUI-64, so
# vmbr0's fe80:: address discloses the host's real *physical* NIC MAC —
# identifying hardware. vmbr10/20/30/40 are software bridges whose MACs are
# randomly generated by the kernel, so their link-locals are retained.
#
# Only the fe80:: token on the vmbr0 line is substituted; every other field
# and every other line passes through untouched.
br_addr_redacted() {
    ip -br addr 2>/dev/null \
        | sed -E '/^vmbr0[[:space:]]/ s#fe80::[0-9a-fA-F:]+/[0-9]+#fe80::[REDACTED-physical-NIC-MAC]#'
}

echo "## Collection metadata"
echo
echo "- Collected (UTC): $(date -u '+%Y-%m-%d %H:%M:%S')"
echo "- Collected on host: $(hostname)"
echo "- Collected by: \`tools/gen-lab-topology.sh\` (read-only)"
echo

# ---------------------------------------------------------------------------
# VM inventory table
# ---------------------------------------------------------------------------
echo "## VM inventory"
echo
echo "Bridge and \`firewall=\` are read from each VM's first \`netN:\` line in"
echo "\`qm config\`. Primary IP is resolved by matching that line's MAC address"
echo "against the Proxmox host's IPv4 neighbour (ARP) table **on the lab bridges"
echo "only** (vmbr10/20/30/40; vmbr0 is excluded so the operator's own LAN devices"
echo "are never captured) — so it reflects an address the host has actually"
echo "observed, not an assumption from the subnet."
echo "A VM that has not recently sent traffic may therefore show UNVERIFIED even"
echo "though it is running and correctly addressed."
echo
echo "Services are not determinable from Proxmox host state (they live inside the"
echo "guests) and are intentionally left blank."
echo
echo "| VMID | Name | Primary IP | Bridge | firewall= | Services |"
echo "|---|---|---|---|---|---|"

vmids="$(qm list 2>/dev/null | awk 'NR>1 {print $1}')"

if [ -z "${vmids}" ]; then
    echo "| UNVERIFIED | UNVERIFIED — \`qm list\` returned nothing; check it runs on this host | | | | |"
else
    for id in ${vmids}; do
        cfg="$(qm config "${id}" 2>/dev/null)"

        name="$(printf '%s\n' "${cfg}" | awk -F': ' '/^name:/ {print $2; exit}')"
        netline="$(printf '%s\n' "${cfg}" | grep -E '^net[0-9]+:' | head -1)"
        bridge="$(printf '%s\n' "${netline}" | grep -o 'bridge=[^,]*' | cut -d= -f2)"
        fw="$(printf '%s\n' "${netline}" | grep -o 'firewall=[^,]*' | cut -d= -f2)"
        mac="$(printf '%s\n' "${netline}" | grep -oiE '([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}' | head -1)"

        vmip=""
        if [ -n "${mac}" ]; then
            vmip="$(lab_neigh \
                    | grep -i -- "${mac}" \
                    | awk '{print $1}' \
                    | head -1)"
        fi

        [ -z "${name}" ]   && name="UNVERIFIED — no name field in qm config"
        [ -z "${bridge}" ] && bridge="UNVERIFIED — no bridge= in netN line"
        [ -z "${fw}" ]     && fw="not set (Proxmox default applies)"
        [ -z "${vmip}" ]   && vmip="UNVERIFIED — MAC not in host ARP cache; check from guest"

        echo "| ${id} | ${name} | ${vmip} | ${bridge} | ${fw} | |"
    done
fi
echo

# Supporting evidence for the IP column above.
# Scoped to lab bridges only — see LAB_BRIDGES above. vmbr0 is deliberately
# excluded so the operator's own LAN devices never appear in this document.
emit "IPv4 neighbour table, lab bridges only (source for the Primary IP column)" lab_neigh
echo

# ---------------------------------------------------------------------------
# Platform
# ---------------------------------------------------------------------------
echo "## Platform"
echo
emit "pveversion -v" pveversion -v
emit "qm list" qm list

echo "### qm config (per VM)"
echo
if [ -z "${vmids}" ]; then
    echo "UNVERIFIED — no VMIDs enumerated."
    echo
else
    for id in ${vmids}; do
        echo "#### VMID ${id}"
        echo
        echo '```'
        qm config "${id}" 2>&1 || echo "UNVERIFIED — qm config ${id} failed"
        echo '```'
        echo
    done
fi

# ---------------------------------------------------------------------------
# Networking
# ---------------------------------------------------------------------------
echo "## Networking"
echo
emit "/etc/network/interfaces" cat /etc/network/interfaces
emit "ip -br addr (vmbr0 IPv6 link-local redacted — see br_addr_redacted)" br_addr_redacted
emit "ip route" ip route

# ---------------------------------------------------------------------------
# Packet filtering
# ---------------------------------------------------------------------------
echo "## Packet filtering"
echo
emit "iptables -t nat -L POSTROUTING -n -v" iptables -t nat -L POSTROUTING -n -v
emit "iptables -L FORWARD -n -v" iptables -L FORWARD -n -v
emit "iptables -L INPUT -n -v" iptables -L INPUT -n -v

echo "### ebtables -L"
echo
echo '```'
ebtables -L 2>/dev/null || echo "ebtables: not present"
echo '```'
echo

emit "sysctl net.bridge.bridge-nf-call-iptables" sysctl net.bridge.bridge-nf-call-iptables

# ---------------------------------------------------------------------------
# Proxmox firewall configuration
# ---------------------------------------------------------------------------
echo "## Proxmox firewall configuration"
echo
echo "### /etc/pve/firewall/cluster.fw"
echo
echo '```'
cat /etc/pve/firewall/cluster.fw 2>/dev/null || echo "UNVERIFIED — cluster.fw not present or unreadable"
echo '```'
echo

echo "### Per-VM .fw files"
echo
shopt -s nullglob
fwfiles=(/etc/pve/firewall/*.fw)
if [ ${#fwfiles[@]} -eq 0 ]; then
    echo "UNVERIFIED — no .fw files found in /etc/pve/firewall/"
    echo
else
    for f in "${fwfiles[@]}"; do
        echo "#### ${f}"
        echo
        echo '```'
        cat "${f}" 2>&1 || echo "UNVERIFIED — could not read ${f}"
        echo '```'
        echo
    done
fi

emit "systemctl is-active pve-firewall proxmox-firewall" \
    systemctl is-active pve-firewall proxmox-firewall
